spring.application.name=Niel-Care-Transportation
#mysql.driver=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/MYDB
serverTimezone=UTC&useSSL=false&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=Itfitfitf@25
spring.security.user.name=user
spring.security.user.password=user

spring.web.resources.static-locations=classpath:/static


# Enable Thymeleaf cache (true by default in production)
spring.thymeleaf.cache=false

# Specify the prefix for the template location (default is classpath:/templates/)
spring.thymeleaf.prefix=classpath:/templates/

# Specify the suffix for the template files (default is .html)
spring.thymeleaf.suffix=.html

# Enable or disable Thymeleaf template engine
spring.thymeleaf.enabled=true

# Set the mode to HTML5 (default is HTML5)
spring.thymeleaf.mode=HTML5

# Set the encoding to UTF-8 (default is UTF-8)
spring.thymeleaf.encoding=UTF-8





spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nilecaretransportation@gmail.com
spring.mail.password=rjputyshdngefbia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true